# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 12:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hitcount.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='제목')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='SLUG')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='설명')),
                ('content', models.TextField(verbose_name='내용')),
                ('image', models.ImageField(upload_to='blog/images/%Y/%d')),
                ('file', models.FileField(upload_to='blog/files/%Y/%d')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='만든날짜')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='수정한 날짜')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['hit_count__hits'],
            },
            bases=(models.Model, hitcount.models.HitCountMixin),
        ),
    ]
